### ISSUE TITLE
Map the failing of Validate::Extract to a specific end

### ISSUE THREAD

**Issue by emaglio** [trailblazer/trailblazer-macro-contract#2]
Map this step https://github.com/trailblazer/trailblazer-macro-contract/blob/master/lib/trailblazer/operation/validate.rb#L18 to fail to a specific end

**Comment by apotonick** [comment]
Implemented, and tested here: https://github.com/trailblazer/trailblazer-macro-contract/blob/master/test/docs/contract_test.rb#L269
